//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string CodigoVerificacion { get; set; }
        public bool Valida { get; set; }
    
        public virtual Usuario Usuario1 { get; set; }
    }
}
